project:
  type: manuscript
  render:
    - "!notes.md"

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  # docx: default
  docx: 
    reference-doc: custom-reference.docx
  # jats: default

  # (other formats)
  pdf: default

execute:
  freeze: auto # Re-render only when source changes.
  cache: true # ensures you don't have to RERUN R or Python if nothing has changed. This will SIGNIFICANTLY boost your rendering speed.



